baseURL: "/"
copyright: Copyright © 2023-{year} [Shiwang](https://dh.211777.xyz). All Rights Reserved.
title: Shiwange NAV

build:
  writeStats: true

# 站点的默认语言
defaultContentLanguage: zh-hans

taxonomies: []

