main:
  - name: Docs
    url: https://hbstack.dev/en/themes/start/
    params:
      icon:
        vendor: bs
        name: book

apps:


# 生活
  - name: Life
    identifier: life
    weight: 1

  - name: 多多进宝
    parent: life
    url: https://jinbao.pinduoduo.com/
    weight: 1

# 工作
  - name: Work
    identifier: work
    weight: 2

  - name: 国家中小学智慧教育平台-教师研修
    parent: work
    url: https://basic.smartedu.cn/teacherTrainingNav
    weight: 1

  - name: 山东省教师教育网 # 继教
    parent: work
    url: https://www.qlteacher.com/
    weight: 2
    
  - name: 重庆人社培训网 # 专技人员公需科目
    parent: work
    url: https://www.cqrspx.cn/
    weight: 3

  - name: 重庆市中小学教师培训学分信息管理系统 # 继教登分系统
    parent: work
    url: http://teacher.jsfz.cqedu.cn/
    weight: 4

  # 电子图书
  - name: eBook
    identifier: ebook
    weight: 3

  - name: Anna’s Archive
    url: https://annas-archive.org/
    weight: 1
    parent: ebook

  # 慕课
  - name: Mooc
    identifier: mooc
    weight: 4

  - name: 中国大学 MOOC
    url: https://www.icourse163.org/
    weight: 1
    parent: mooc

  # 人工智能
  - name: AI
    identifier: ai
    weight: 5

  - name: DeeSeek（深度求索）
    url: https://www.deepseek.com/
    weight: 1
    parent: ai

  # 操作系统
  - name: OS
    identifier: os
    weight: 6

  - name: 山己几子木
    url: https://msdn.sjjzm.com
    weight: 1
    parent: os

  # 电脑软件
  - name: Software
    identifier: software
    weight: 7

  - name: Download
    url: https://downloadlynet.ir/
    weight: 1
    parent: software

  # 手机软件
  - name: App
    identifier: app
    weight: 8

  - name: FM影视TV
    parent: app
    url: https://github.com/FongMi/Release/raw/fongmi/apk/release
    weight: 1

  - name: OK影视TV
    parent: app
    url: https://github.com/FongMi/Release/blob/main/apk/release
    weight: 2


  # 翻译
  - name: Transl
    identifier: transl
    weight: 9

  - name: 爱词霸
    url: https://www.iciba.com/translate
    weight: 1
    parent: transl

  # 在线工具
  - name: Onlinetool
    identifier: onlinetool
    weight: 10

  - name: 在线屏幕检测
    url: https://screen.bmcx.com/#welcome
    weight: 1
    parent: onlinetool

  # 站长工具
  - name: Webmaster
    identifier: webmaster
    weight: 11

  - name: GitHub
    url: https://github.com
    weight: 1
    parent: webmaster
